Insert into REGIONS (REGION_ID,REGION_NAME,COUNTRY_NAME) values (1,'EAST','INDIA');
Insert into REGIONS (REGION_ID,REGION_NAME,COUNTRY_NAME) values (2,'WEST','INDIA');
Insert into REGIONS (REGION_ID,REGION_NAME,COUNTRY_NAME) values (3,'CENTRAL','INDIA');
Insert into REGIONS (REGION_ID,REGION_NAME,COUNTRY_NAME) values (4,'SOUTH','INDIA');
Insert into REGIONS (REGION_ID,REGION_NAME,COUNTRY_NAME) values (5,'EAST-WEST','INDIA');
Insert into BRANCH_MASTER (BRANCH_ID,BRANCH_CODE,ADDRESS1,ADDRESS2,BRANCH_CITY,BRANCH_STATE,PIN_CODE,IFSC_CODE,REGION_ID,BRANCH_MAIL) values (7,'SB00033','Mount Abu Road',null,'Mount Abu','Rajasthan','380050','SBIN00001',2,'abcd@some.com');
Insert into BRANCH_MASTER (BRANCH_ID,BRANCH_CODE,ADDRESS1,ADDRESS2,BRANCH_CITY,BRANCH_STATE,PIN_CODE,IFSC_CODE,REGION_ID,BRANCH_MAIL) values (1,'SB00001','Maninagar Station Road',null,'Ahmedabad','Gujarat','380050','SBIN00001',2,'abcd@some.com');
Insert into BRANCH_MASTER (BRANCH_ID,BRANCH_CODE,ADDRESS1,ADDRESS2,BRANCH_CITY,BRANCH_STATE,PIN_CODE,IFSC_CODE,REGION_ID,BRANCH_MAIL) values (2,'SB00002','Bhandarkar Road',null,'Pune','Maharashtra','411007','SBIN00002',2,'abcd@def.com');
Insert into BRANCH_MASTER (BRANCH_ID,BRANCH_CODE,ADDRESS1,ADDRESS2,BRANCH_CITY,BRANCH_STATE,PIN_CODE,IFSC_CODE,REGION_ID,BRANCH_MAIL) values (3,'SB00003','Shaktinagar','MPEB Colony','Jabalpur','Madhya Pradesh','482001','SBIN00105',3,'abcd@def.com');
Insert into BRANCH_MASTER (BRANCH_ID,BRANCH_CODE,ADDRESS1,ADDRESS2,BRANCH_CITY,BRANCH_STATE,PIN_CODE,IFSC_CODE,REGION_ID,BRANCH_MAIL) values (4,'SB00002','Aundh',null,'Pune','Maharashtra','411007','SBIN00002',2,'abcd@def.com');
commit;
Insert into BRANCH_MASTER (BRANCH_ID,BRANCH_CODE,ADDRESS1,ADDRESS2,BRANCH_CITY,BRANCH_STATE,PIN_CODE,IFSC_CODE,REGION_ID,BRANCH_MAIL) values (5,'SB00003','Akurdi',null,'Pune','Maharashtra','411035','SBIN00003',2,'abcd@def.com');
Insert into BRANCH_MASTER (BRANCH_ID,BRANCH_CODE,ADDRESS1,ADDRESS2,BRANCH_CITY,BRANCH_STATE,PIN_CODE,IFSC_CODE,REGION_ID,BRANCH_MAIL) values (6,'SB00003','Akurdi',null,'Pune','Maharashtra','411035','SBIN00003',2,'abcd@def.com');
INSERT INTO USER (USER_ID,FIRST_NAME,LAST_NAME,BLOOD_GROUP,EMAIL_ID,PASSWORD) VALUES(1,'HARDIK','BHANGALE','O+','bhangalehardik@gmail.com','ABCD@1234');
INSERT INTO USER (USER_ID,FIRST_NAME,LAST_NAME,BLOOD_GROUP,EMAIL_ID,PASSWORD) VALUES(2,'ADITI','BHANGALE','O+','aditipail276@gmail.comm','ABCD@1234');
INSERT INTO USER (USER_ID,FIRST_NAME,LAST_NAME,BLOOD_GROUP,EMAIL_ID,PASSWORD) VALUES(3,'ADMIN','USER','O+','3.hardik@gmail.com','ABCD@1234');

commit;